% Author: Luis Badesa
%
% This code is a simple example of an Economic Dispatch optimisation,
% intended to teach how to create a simple optimisation problem in YALMIP.

%% Input Data
cost = [5 10 15]'; % £/MWh
Power_limits = [20 20 20]'; % MW
Demand = 50; % MW

%% Create the model for the optimisation
% Define Decision Variables for power generated by each unit:
power = sdpvar(length(cost),1); % MW

% Define the constraints:
Power_limits = 0 <= power <= Power_limits;           
Power_balance = sum(power) == Demand;

Constraints = [Power_limits,...
               Power_balance];

% Define the objective function (in this case we want to minimise the total
% cost of producing energy):
Cost = cost'*power;
Objective = Cost;
           
%% Solve the optimisation
% Solver settings:
options = sdpsettings('solver','gurobi');

% Call the solver:
sol = optimize(Constraints,Objective,options)

%% Get the solution
Total_Cost = value(Objective) % £
Power_generated = value(power) % MW
MarginalPrice_energy = -dual(Power_balance) % £/MWh
